### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by Astate** [lordi/docker-teamviewer#1] opened 2015-04-26 17:52 UTC
Hello, the network dont work here.
i am on linux Kaos.

**Comment by lordi** [comment] 2015-05-04 08:20
Sorry, I don't actively maintain this repository

**Comment by lordi** [comment] 2016-02-27 17:59
Sorry for waking the dead but does #2 solve your problem?

**Comment by Astate** [comment] 2016-02-27 19:03
Setting up libxrender1:i386 (1:0.9.9-2) ...
Setting up libxrandr2:i386 (2:1.5.0-1) ...
Setting up sudo (1.8.15-1.1) ...
Setting up publicsuffix (20160130-1) ...
Processing triggers for libc-bin (2.21-9) ...
Processing triggers for systemd (229-1) ...
Processing triggers for ca-certificates (20160104) ...
Updating certificates in /etc/ssl/certs...
173 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
/bin/sh: 1: libdbus-1-3:i386: not found
The command '/bin/sh -c dpkg --add-architecture i386 &&     apt-get -q update &&     apt-get -q upgrade -    apt-get -q install -y adduser libasound2:i386 libc6:i386 libfreetype6:i386         libgcc1:i386 libsm6 libxdamage1:i386 libxext6:i386         libxfixes3:i386 libxrandr2:i386 libxrender1:i386 libxtst6:i386 s       wget zlib1g:i386 libjpeg8:i386 libexpat1:i386 fonts-liberation:i386         libfontconfig1:i386 fofig-config:i386 ucf &&         libdbus-1-3:i386 libjpeg62:i386 libxinerama1:i386 &&     echo "hybris    ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/hybris' returned a non-zero code: 127
Unable to find image 'teamviewer:latest' locally
Pulling repository docker.io/library/teamviewer
docker: Error: image library/teamviewer not found.
See 'docker run --help'.

**Comment by joonas-fi** [comment] 2016-05-07 12:19
It's not a network issue. The issue is here:

```
/bin/sh: 1: libdbus-1-3:i386: not found
```

I.e. there shouldn't be "&&" before "libdbus-1-3:i386" in the apt-get command.

That is causing the Docker build to fail, and thus since the image we tried to build just now (but failed), is tried to fetch from Docker hub (incorrectly), it might look like a network issue.

I didn't see the "&&" in the Dockerfile, so I'm baffled why it's in your command output.

P.s. maybe you should stick this to the Bash script, so if image build fails, the container will not be tried to start:

```
set -e
```

Edit: oh sorry, looking at the history of `Dockerfile`, the extra "&&" actually existed. This fixes it: https://github.com/lordi/docker-teamviewer/commit/54e61cda6125b484aaf9db7ec0e3e8253cb2f3bf

**Comment by lordi** [comment] 2016-05-08 15:53
Thanks for the info anyway, I'm closing this issue. Feel free to open another one if you have any problems.

**Closed as completed by lordi** 2016-05-08 15:53 UTC
